#!/usr/bin/env bash
# Pull secrets from AWS Secrets Manager and write them to /opt/kla-pusher/.env.secrets.
#
# Runs as systemd ExecStartPre on every kla-pusher start. Reads the shared
# `kla-secrets-production` JSON bundle that the rest of the platform also uses
# (kla-devops/production/secrets/vars.json mirrors its shape).
#
# Output file is loaded alongside the hand-managed /opt/kla-pusher/.env, which
# holds non-secret config (PORT, REGISTRY_SOURCE, BC24_*, URLs). The two
# EnvironmentFile= lines in the systemd unit merge them at process start.
#
# Authentication: the EC2 instance profile (kla-pusher-production-profile)
# grants `secretsmanager:GetSecretValue` on this one secret ARN. No static
# AWS credentials live on the host.

set -euo pipefail

SECRET_ID=${SECRET_ID:-kla-secrets-production}
REGION=${AWS_REGION:-ap-southeast-1}
OUTFILE=${OUTFILE:-/opt/kla-pusher/.env.secrets}

# Atomic write — render to a temp file then mv, so a partial fetch can't
# leave kla-pusher staring at half-written env vars on restart.
TMP=$(mktemp "${OUTFILE}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_ID" \
  --region "$REGION" \
  --query SecretString \
  --output text)

# Field plucks: each line adds one VAR=value pair to the output file.
# Keep the list minimal — only secrets that kla-pusher actually consumes.
# Non-secret BC24 config (LOGIN_URL, SOCKET_URL, ORIGIN) still lives in .env.
{
  echo "# Generated by render-env.sh at $(date -u +%FT%TZ). Do not edit by hand."
  printf 'SITE_API_SERVICE_TOKEN=%s\n' "$(jq -r '.site_api.service_token' <<<"$JSON")"
  printf 'BC24_USERNAME=%s\n' "$(jq -r '.bc24.username' <<<"$JSON")"
  printf 'BC24_PASSWORD=%s\n' "$(jq -r '.bc24.password' <<<"$JSON")"
} >"$TMP"

# 0600 — readable by the kla-pusher service user via group/ownership set below.
chmod 0600 "$TMP"
chown kla-pusher:kla-pusher "$TMP"
mv "$TMP" "$OUTFILE"
trap - EXIT
