#!/usr/bin/env bash
# Pull ALL kla-pusher config from AWS Secrets Manager and write it to
# /opt/kla-pusher/.env.secrets.
#
# Runs as systemd ExecStartPre on every kla-pusher start. Reads the shared
# `kla-secrets-production` JSON bundle that the rest of the platform also uses
# (kla-devops/production/secrets/vars.json mirrors its shape).
#
# Every env var the pusher consumes (see src/env.ts) is sourced here — both
# the real secrets (service token, bc24 credentials) and the non-secret
# config (PORT, REGISTRY_SOURCE, SITE_API_BASE_URL, BC24 URLs, …). This makes
# the box self-healing: a re-provisioned instance reconstructs its entire env
# from Secrets Manager on first boot, so there is no hand-managed /opt/kla-pusher/.env
# to lose. The systemd unit still loads /opt/kla-pusher/.env first (if present)
# and this file second, so .env may be absent or used only for local overrides.
#
# Authentication: the EC2 instance profile (kla-pusher-production-profile)
# grants `secretsmanager:GetSecretValue` on this one secret ARN. No static
# AWS credentials live on the host, and no AWS SDK is bundled into the Node app.

set -euo pipefail

SECRET_ID=${SECRET_ID:-kla-secrets-production}
REGION=${AWS_REGION:-ap-southeast-1}
OUTFILE=${OUTFILE:-/opt/kla-pusher/.env.secrets}

# Atomic write — render to a temp file then mv, so a partial fetch can't
# leave kla-pusher staring at half-written env vars on restart.
TMP=$(mktemp "${OUTFILE}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_ID" \
  --region "$REGION" \
  --query SecretString \
  --output text)

# Pull a value by jq path, failing loudly if it is null/absent — a missing key
# almost always means the bundle and src/env.ts have drifted, and we'd rather
# refuse to boot than start with a silently-wrong config.
pluck() {
  local path=$1
  local val
  val=$(jq -er "$path" <<<"$JSON") || {
    echo "render-env.sh: missing required key '$path' in $SECRET_ID" >&2
    exit 1
  }
  printf '%s' "$val"
}

# Every var from src/env.ts. Secrets + non-secret config, all from the bundle.
{
  echo "# Generated by render-env.sh at $(date -u +%FT%TZ). Do not edit by hand."
  # --- secrets ---
  printf 'SITE_API_SERVICE_TOKEN=%s\n' "$(pluck '.site_api.service_token')"
  printf 'BC24_USERNAME=%s\n'          "$(pluck '.bc24.username')"
  printf 'BC24_PASSWORD=%s\n'          "$(pluck '.bc24.password')"
  # --- non-secret config (pusher section) ---
  printf 'PORT=%s\n'                      "$(pluck '.pusher.port')"
  printf 'REGISTRY_SOURCE=%s\n'           "$(pluck '.pusher.registry_source')"
  printf 'STREAMS_REGISTRY_FILE=%s\n'     "$(pluck '.pusher.streams_registry_file')"
  printf 'SITE_API_BASE_URL=%s\n'         "$(pluck '.pusher.site_api_base_url')"
  printf 'REGISTRY_GAME_IDS=%s\n'         "$(pluck '.pusher.registry_game_ids')"
  printf 'REGISTRY_POLL_INTERVAL_MS=%s\n' "$(pluck '.pusher.registry_poll_interval_ms')"
  printf 'BC24_LOGIN_URL=%s\n'            "$(pluck '.pusher.bc24_login_url')"
  printf 'BC24_SOCKET_URL=%s\n'           "$(pluck '.pusher.bc24_socket_url')"
  printf 'BC24_ORIGIN=%s\n'               "$(pluck '.pusher.bc24_origin')"
} >"$TMP"

# 0600 — readable by the kla-pusher service user via group/ownership set below.
chmod 0600 "$TMP"
chown kla-pusher:kla-pusher "$TMP"
mv "$TMP" "$OUTFILE"
trap - EXIT
